// <auto-generated />
using System;
using Legacy.Maliev.AccountingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legacy.Maliev.AccountingService.Data.Migrations.Receipt
{
    [DbContext(typeof(ReceiptDbContext))]
    [Migration("20260715055545_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Receipt.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmountPaid")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComputedColumnSql("(\"Total\" - COALESCE(\"WithholdingTax\", 0))::numeric(18,2)", true);

                    b.Property<string>("BillingAddressBuilding")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressCity")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressCompany")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressCountry")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressRecipient")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressState")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("CommercialRegistration")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("CustomerID");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TaxIdentification")
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Vat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VAT");

                    b.Property<decimal?>("WithholdingTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Receipt");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Receipt.ReceiptFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bucket")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ObjectName")
                        .HasColumnType("text");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("ReceiptID");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptFile");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Receipt.ReceiptOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("ReceiptID");

                    b.Property<decimal?>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComputedColumnSql("(\"UnitPrice\" * \"Quantity\")::numeric(18,2)", true);

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Receipt.ReceiptFile", b =>
                {
                    b.HasOne("Legacy.Maliev.AccountingService.Domain.Receipt.Receipt", "Receipt")
                        .WithMany("ReceiptFile")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ReceiptFile_Receipt");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Receipt.ReceiptOrderItem", b =>
                {
                    b.HasOne("Legacy.Maliev.AccountingService.Domain.Receipt.Receipt", "Receipt")
                        .WithMany("ReceiptOrderItem")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_OrderItem_Receipt");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Receipt.Receipt", b =>
                {
                    b.Navigation("ReceiptFile");

                    b.Navigation("ReceiptOrderItem");
                });
#pragma warning restore 612, 618
        }
    }
}
