// <auto-generated />
using System;
using Legacy.Maliev.AccountingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legacy.Maliev.AccountingService.Data.Migrations.Invoice
{
    [DbContext(typeof(InvoiceDbContext))]
    [Migration("20261006140000_RetainInvoiceFinancialOwnership")]
    partial class RetainInvoiceFinancialOwnership
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Data.InvoiceCreationAdmission", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("OperationID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeCompletionJson")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FinancialOwnershipJson")
                        .HasColumnType("text");

                    b.Property<string>("FinancialResultJson")
                        .HasColumnType("text");

                    b.Property<string>("IntentFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OriginIssuer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("QuotationId")
                        .HasColumnType("integer")
                        .HasColumnName("QuotationID");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<string>("ServiceSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OperationId");

                    b.ToTable("InvoiceCreationAdmission", t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceCreationAdmission_Quotation", "\"QuotationID\" > 0");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Data.InvoiceNotificationCorrelationRow", b =>
                {
                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("IntentID");

                    b.Property<DateTimeOffset?>("AdmissionIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BindingKeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("BindingKeyID");

                    b.Property<string>("BindingVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExecutionIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("InvoiceID");

                    b.Property<string>("OriginEmployeeSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OriginIssuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OriginServiceSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("PayloadBinding")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PayloadFrameVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("QuotationId")
                        .HasColumnType("integer")
                        .HasColumnName("QuotationID");

                    b.Property<DateTimeOffset?>("RemoteAdmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RemoteReceiptBinding")
                        .HasColumnType("bytea");

                    b.Property<string>("RemoteState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("RemoteUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("RemoteVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("SenderIssuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SenderServiceSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkflowOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowOperationID");

                    b.HasKey("IntentId")
                        .HasName("PK_InvoiceNotificationCorrelation");

                    b.HasAlternateKey("InvoiceId", "Purpose")
                        .HasName("UQ_InvoiceNotificationCorrelation_InvoicePurpose");

                    b.ToTable("InvoiceNotificationCorrelation", "public", t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceNotificationCorrelation_Identity", "\"InvoiceID\" > 0 AND \"QuotationID\" > 0 AND \"Purpose\" = 'invoice-issued'\nAND \"SenderServiceSubject\" = 'service:legacy-accounting'\nAND \"IntentID\" <> '00000000-0000-0000-0000-000000000000'::uuid\nAND \"WorkflowOperationID\" <> '00000000-0000-0000-0000-000000000000'::uuid\nAND \"IntentID\" <> \"WorkflowOperationID\"\nAND octet_length(\"PayloadBinding\") = 32\nAND length(\"OriginIssuer\") > 0 AND length(\"OriginEmployeeSubject\") > 0\nAND length(\"OriginServiceSubject\") > 0 AND length(\"SenderIssuer\") > 0\nAND length(\"BindingKeyID\") > 0\nAND \"PayloadFrameVersion\" = 'notification-payload-v1'\nAND \"BindingVersion\" = 'accounting-invoice-notification-hmac-v1'");

                            t.HasCheckConstraint("CK_InvoiceNotificationCorrelation_Receipt", "(\"RemoteVersion\" IS NULL AND \"RemoteState\" IS NULL AND\n \"RemoteAdmittedAt\" IS NULL AND \"RemoteUpdatedAt\" IS NULL AND \"RemoteReceiptBinding\" IS NULL)\nOR\n(\"RemoteVersion\" IS NOT NULL AND \"RemoteVersion\">0 AND \"RemoteState\" IS NOT NULL AND\n \"RemoteAdmittedAt\" IS NOT NULL AND \"RemoteUpdatedAt\" IS NOT NULL AND\n \"RemoteReceiptBinding\" IS NOT NULL AND octet_length(\"RemoteReceiptBinding\")=32 AND\n \"RemoteUpdatedAt\">=\"RemoteAdmittedAt\" AND\n ((\"RemoteState\"='admitted' AND \"RemoteVersion\"=1) OR\n  (\"RemoteState\"='submitting' AND \"RemoteVersion\"=2) OR\n  (\"RemoteState\" IN ('outcomeUnknown','providerAccepted') AND \"RemoteVersion\"=3)))");

                            t.HasCheckConstraint("CK_InvoiceNotificationCorrelation_ReceiptPhase", "(\"Phase\" IN ('Prepared','AdmissionIssued') AND \"RemoteVersion\" IS NULL)\nOR (\"Phase\" IN ('Admitted','ExecutionIssued') AND \"RemoteVersion\" IS NOT NULL AND \"RemoteState\"='admitted')\nOR (\"Phase\"='OutcomeUnknown' AND \"RemoteVersion\" IS NOT NULL AND \"RemoteState\" IN ('submitting','outcomeUnknown'))\nOR (\"Phase\"='ProviderAccepted' AND \"RemoteVersion\" IS NOT NULL AND \"RemoteState\"='providerAccepted')");

                            t.HasCheckConstraint("CK_InvoiceNotificationCorrelation_State", "\"Version\" > 0 AND (\"RemoteVersion\" IS NULL OR \"RemoteVersion\" > 0)\nAND \"UpdatedAt\" >= \"CreatedAt\"\nAND \"Phase\" IN ('Prepared','AdmissionIssued','Admitted','ExecutionIssued',\n                'OutcomeUnknown','ProviderAccepted','RejectedBeforeSubmission')\nAND (\"AdmissionIssuedAt\" IS NULL OR \"AdmissionIssuedAt\" >= \"CreatedAt\")\nAND (\"ExecutionIssuedAt\" IS NULL OR\n  (\"AdmissionIssuedAt\" IS NOT NULL AND \"ExecutionIssuedAt\" >= \"AdmissionIssuedAt\"))\nAND (\"Phase\" = 'Prepared' OR \"AdmissionIssuedAt\" IS NOT NULL)\nAND (\"Phase\" <> 'Prepared' OR\n  (\"AdmissionIssuedAt\" IS NULL AND \"ExecutionIssuedAt\" IS NULL AND \"RemoteVersion\" IS NULL))\nAND (\"Phase\" <> 'AdmissionIssued' OR\n  (\"AdmissionIssuedAt\" IS NOT NULL AND \"ExecutionIssuedAt\" IS NULL))\nAND (\"Phase\" <> 'Admitted' OR\n  (\"AdmissionIssuedAt\" IS NOT NULL AND \"ExecutionIssuedAt\" IS NULL AND \"RemoteVersion\" IS NOT NULL))\nAND (\"Phase\" <> 'ExecutionIssued' OR\n  (\"ExecutionIssuedAt\" IS NOT NULL AND \"RemoteVersion\" IS NOT NULL))\nAND (\"Phase\" NOT IN ('OutcomeUnknown','ProviderAccepted') OR\n  (\"ExecutionIssuedAt\" IS NOT NULL AND \"RemoteVersion\" IS NOT NULL))\nAND (\"Phase\" NOT IN ('ProviderAccepted','RejectedBeforeSubmission') OR \"RemoteVersion\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddressBuilding")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressCity")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressCompany")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressCountry")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressRecipient")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressState")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("CommercialRegistration")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Fob")
                        .HasColumnType("text");

                    b.Property<string>("InternalComment")
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<decimal?>("Outstanding")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasColumnType("text");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("ReceiptID");

                    b.Property<string>("Requisitioner")
                        .HasColumnType("text");

                    b.Property<string>("SalesPerson")
                        .HasColumnType("text");

                    b.Property<string>("ShippedVia")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressBuilding")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressCity")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressCompany")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressCountry")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressRecipient")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressRecipientTelephone")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressState")
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceJourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceJourneyID");

                    b.Property<int?>("SourceRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("SourceRequestID");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TaxIdentification")
                        .HasColumnType("text");

                    b.Property<string>("Terms")
                        .HasColumnType("text");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Vat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("WithholdingTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SourceJourneyId")
                        .HasFilter("\"SourceJourneyID\" IS NOT NULL");

                    b.HasIndex("SourceRequestId")
                        .HasFilter("\"SourceRequestID\" IS NOT NULL");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.InvoiceFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bucket")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("InvoiceID");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("ObjectName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceFile");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.InvoiceOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("InvoiceID");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComputedColumnSql("(\"UnitPrice\" * \"Quantity\")::numeric(18,2)", true);

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.InvoiceFile", b =>
                {
                    b.HasOne("Legacy.Maliev.AccountingService.Domain.Invoice.Invoice", "Invoice")
                        .WithMany("InvoiceFiles")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceFile_Invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.InvoiceOrderItem", b =>
                {
                    b.HasOne("Legacy.Maliev.AccountingService.Domain.Invoice.Invoice", "Invoice")
                        .WithMany("InvoiceOrderItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_OrderItem_Invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.Invoice", b =>
                {
                    b.Navigation("InvoiceFiles");

                    b.Navigation("InvoiceOrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
