// <auto-generated />
using System;
using Legacy.Maliev.AccountingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legacy.Maliev.AccountingService.Data.Migrations.Invoice
{
    [DbContext(typeof(InvoiceDbContext))]
    [Migration("20260715055541_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddressBuilding")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressCity")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressCompany")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressCountry")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressRecipient")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressState")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("CommercialRegistration")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Fob")
                        .HasColumnType("text")
                        .HasColumnName("FOB");

                    b.Property<string>("InternalComment")
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<decimal?>("Outstanding")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasColumnType("text");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("ReceiptID");

                    b.Property<string>("Requisitioner")
                        .HasColumnType("text");

                    b.Property<string>("SalesPerson")
                        .HasColumnType("text");

                    b.Property<string>("ShippedVia")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressBuilding")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressCity")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressCompany")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressCountry")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressRecipient")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressRecipientTelephone")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressState")
                        .HasColumnType("text");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TaxIdentification")
                        .HasColumnType("text");

                    b.Property<string>("Terms")
                        .HasColumnType("text");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Vat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VAT");

                    b.Property<decimal?>("WithholdingTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.InvoiceFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bucket")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("InvoiceID");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ObjectName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceFile");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.InvoiceOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("InvoiceID");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComputedColumnSql("(\"UnitPrice\" * \"Quantity\")::numeric(18,2)", true);

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.InvoiceFile", b =>
                {
                    b.HasOne("Legacy.Maliev.AccountingService.Domain.Invoice.Invoice", "Invoice")
                        .WithMany("InvoiceFiles")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceFile_Invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.InvoiceOrderItem", b =>
                {
                    b.HasOne("Legacy.Maliev.AccountingService.Domain.Invoice.Invoice", "Invoice")
                        .WithMany("InvoiceOrderItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_OrderItem_Invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.Invoice", b =>
                {
                    b.Navigation("InvoiceFiles");

                    b.Navigation("InvoiceOrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
