// <auto-generated />
using System;
using Legacy.Maliev.AccountingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legacy.Maliev.AccountingService.Data.Migrations.Invoice
{
    [DbContext(typeof(InvoiceDbContext))]
    [Migration("20261007100000_RequireInvoiceMasterSourceStrings")]
    partial class RequireInvoiceMasterSourceStrings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Data.InvoiceCreationAdmission", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("OperationID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeCompletionJson")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FinancialOwnershipJson")
                        .HasColumnType("text");

                    b.Property<string>("FinancialResultJson")
                        .HasColumnType("text");

                    b.Property<string>("IntentFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OriginIssuer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("QuotationId")
                        .HasColumnType("integer")
                        .HasColumnName("QuotationID");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<string>("ServiceSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OperationId");

                    b.ToTable("InvoiceCreationAdmission", t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceCreationAdmission_Quotation", "\"QuotationID\" > 0");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Data.InvoiceNotificationCorrelationRow", b =>
                {
                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("IntentID");

                    b.Property<DateTimeOffset?>("AdmissionIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BindingKeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("BindingKeyID");

                    b.Property<string>("BindingVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExecutionIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("InvoiceID");

                    b.Property<string>("OriginEmployeeSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OriginIssuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OriginServiceSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("PayloadBinding")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PayloadFrameVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("QuotationId")
                        .HasColumnType("integer")
                        .HasColumnName("QuotationID");

                    b.Property<DateTimeOffset?>("RemoteAdmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RemoteReceiptBinding")
                        .HasColumnType("bytea");

                    b.Property<string>("RemoteState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("RemoteUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("RemoteVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("SenderIssuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SenderServiceSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkflowOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowOperationID");

                    b.HasKey("IntentId")
                        .HasName("PK_InvoiceNotificationCorrelation");

                    b.HasAlternateKey("InvoiceId", "Purpose")
                        .HasName("UQ_InvoiceNotificationCorrelation_InvoicePurpose");

                    b.ToTable("InvoiceNotificationCorrelation", "public", t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceNotificationCorrelation_Identity", "\"InvoiceID\" > 0 AND \"QuotationID\" > 0 AND \"Purpose\" = 'invoice-issued'\nAND \"SenderServiceSubject\" = 'service:legacy-accounting'\nAND \"IntentID\" <> '00000000-0000-0000-0000-000000000000'::uuid\nAND \"WorkflowOperationID\" <> '00000000-0000-0000-0000-000000000000'::uuid\nAND \"IntentID\" <> \"WorkflowOperationID\"\nAND octet_length(\"PayloadBinding\") = 32\nAND length(\"OriginIssuer\") > 0 AND length(\"OriginEmployeeSubject\") > 0\nAND length(\"OriginServiceSubject\") > 0 AND length(\"SenderIssuer\") > 0\nAND length(\"BindingKeyID\") > 0\nAND \"PayloadFrameVersion\" = 'notification-payload-v1'\nAND \"BindingVersion\" = 'accounting-invoice-notification-hmac-v1'");

                            t.HasCheckConstraint("CK_InvoiceNotificationCorrelation_Receipt", "(\"RemoteVersion\" IS NULL AND \"RemoteState\" IS NULL AND\n \"RemoteAdmittedAt\" IS NULL AND \"RemoteUpdatedAt\" IS NULL AND \"RemoteReceiptBinding\" IS NULL)\nOR\n(\"RemoteVersion\" IS NOT NULL AND \"RemoteVersion\">0 AND \"RemoteState\" IS NOT NULL AND\n \"RemoteAdmittedAt\" IS NOT NULL AND \"RemoteUpdatedAt\" IS NOT NULL AND\n \"RemoteReceiptBinding\" IS NOT NULL AND octet_length(\"RemoteReceiptBinding\")=32 AND\n \"RemoteUpdatedAt\">=\"RemoteAdmittedAt\" AND\n ((\"RemoteState\"='admitted' AND \"RemoteVersion\"=1) OR\n  (\"RemoteState\"='submitting' AND \"RemoteVersion\"=2) OR\n  (\"RemoteState\" IN ('outcomeUnknown','providerAccepted') AND \"RemoteVersion\"=3)))");

                            t.HasCheckConstraint("CK_InvoiceNotificationCorrelation_ReceiptPhase", "(\"Phase\" IN ('Prepared','AdmissionIssued') AND \"RemoteVersion\" IS NULL)\nOR (\"Phase\" IN ('Admitted','ExecutionIssued') AND \"RemoteVersion\" IS NOT NULL AND \"RemoteState\"='admitted')\nOR (\"Phase\"='OutcomeUnknown' AND \"RemoteVersion\" IS NOT NULL AND \"RemoteState\" IN ('submitting','outcomeUnknown'))\nOR (\"Phase\"='ProviderAccepted' AND \"RemoteVersion\" IS NOT NULL AND \"RemoteState\"='providerAccepted')");

                            t.HasCheckConstraint("CK_InvoiceNotificationCorrelation_State", "\"Version\" > 0 AND (\"RemoteVersion\" IS NULL OR \"RemoteVersion\" > 0)\nAND \"UpdatedAt\" >= \"CreatedAt\"\nAND \"Phase\" IN ('Prepared','AdmissionIssued','Admitted','ExecutionIssued',\n                'OutcomeUnknown','ProviderAccepted','RejectedBeforeSubmission')\nAND (\"AdmissionIssuedAt\" IS NULL OR \"AdmissionIssuedAt\" >= \"CreatedAt\")\nAND (\"ExecutionIssuedAt\" IS NULL OR\n  (\"AdmissionIssuedAt\" IS NOT NULL AND \"ExecutionIssuedAt\" >= \"AdmissionIssuedAt\"))\nAND (\"Phase\" = 'Prepared' OR \"AdmissionIssuedAt\" IS NOT NULL)\nAND (\"Phase\" <> 'Prepared' OR\n  (\"AdmissionIssuedAt\" IS NULL AND \"ExecutionIssuedAt\" IS NULL AND \"RemoteVersion\" IS NULL))\nAND (\"Phase\" <> 'AdmissionIssued' OR\n  (\"AdmissionIssuedAt\" IS NOT NULL AND \"ExecutionIssuedAt\" IS NULL))\nAND (\"Phase\" <> 'Admitted' OR\n  (\"AdmissionIssuedAt\" IS NOT NULL AND \"ExecutionIssuedAt\" IS NULL AND \"RemoteVersion\" IS NOT NULL))\nAND (\"Phase\" <> 'ExecutionIssued' OR\n  (\"ExecutionIssuedAt\" IS NOT NULL AND \"RemoteVersion\" IS NOT NULL))\nAND (\"Phase\" NOT IN ('OutcomeUnknown','ProviderAccepted') OR\n  (\"ExecutionIssuedAt\" IS NOT NULL AND \"RemoteVersion\" IS NOT NULL))\nAND (\"Phase\" NOT IN ('ProviderAccepted','RejectedBeforeSubmission') OR \"RemoteVersion\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddressBuilding")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressCity")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressCompany")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressCountry")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressLine1")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressLine2")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressPostalCode")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressRecipient")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressState")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("CommercialRegistration")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Currency")
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Fob")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("InternalComment")
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.Property<decimal?>("Outstanding")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("ReceiptID");

                    b.Property<string>("Requisitioner")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("SalesPerson")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("ShippedVia")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressBuilding")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressCity")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressCompany")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressCountry")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressLine1")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressLine2")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressPostalCode")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressRecipient")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressRecipientTelephone")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressState")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceJourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceJourneyID");

                    b.Property<int?>("SourceRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("SourceRequestID");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TaxIdentification")
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.Property<string>("Terms")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Vat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("WithholdingTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SourceJourneyId")
                        .HasFilter("\"SourceJourneyID\" IS NOT NULL");

                    b.HasIndex("SourceRequestId")
                        .HasFilter("\"SourceRequestID\" IS NOT NULL");

                    b.ToTable("Invoice", t =>
                        {
                            t.HasCheckConstraint("CK_Invoice_BillingAddressBuilding_SourceLength", "char_length(\"BillingAddressBuilding\") + char_length(regexp_replace(\"BillingAddressBuilding\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_BillingAddressCity_SourceLength", "char_length(\"BillingAddressCity\") + char_length(regexp_replace(\"BillingAddressCity\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_BillingAddressCompany_SourceLength", "char_length(\"BillingAddressCompany\") + char_length(regexp_replace(\"BillingAddressCompany\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_BillingAddressCountry_SourceLength", "char_length(\"BillingAddressCountry\") + char_length(regexp_replace(\"BillingAddressCountry\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_BillingAddressLine1_SourceLength", "char_length(\"BillingAddressLine1\") + char_length(regexp_replace(\"BillingAddressLine1\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_BillingAddressLine2_SourceLength", "char_length(\"BillingAddressLine2\") + char_length(regexp_replace(\"BillingAddressLine2\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_BillingAddressPostalCode_SourceLength", "char_length(\"BillingAddressPostalCode\") + char_length(regexp_replace(\"BillingAddressPostalCode\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_BillingAddressRecipient_SourceLength", "char_length(\"BillingAddressRecipient\") + char_length(regexp_replace(\"BillingAddressRecipient\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_BillingAddressState_SourceLength", "char_length(\"BillingAddressState\") + char_length(regexp_replace(\"BillingAddressState\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_CommercialRegistration_SourceLength", "char_length(\"CommercialRegistration\") + char_length(regexp_replace(\"CommercialRegistration\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_Currency_SourceLength", "char_length(\"Currency\") + char_length(regexp_replace(\"Currency\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 50");
                            t.HasCheckConstraint("CK_Invoice_Fob_SourceLength", "char_length(\"Fob\") + char_length(regexp_replace(\"Fob\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_Number_SourceLength", "char_length(\"Number\") + char_length(regexp_replace(\"Number\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 100");
                            t.HasCheckConstraint("CK_Invoice_PurchaseOrderNumber_SourceLength", "char_length(\"PurchaseOrderNumber\") + char_length(regexp_replace(\"PurchaseOrderNumber\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_Requisitioner_SourceLength", "char_length(\"Requisitioner\") + char_length(regexp_replace(\"Requisitioner\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_SalesPerson_SourceLength", "char_length(\"SalesPerson\") + char_length(regexp_replace(\"SalesPerson\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_ShippedVia_SourceLength", "char_length(\"ShippedVia\") + char_length(regexp_replace(\"ShippedVia\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_ShippingAddressBuilding_SourceLength", "char_length(\"ShippingAddressBuilding\") + char_length(regexp_replace(\"ShippingAddressBuilding\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_ShippingAddressCity_SourceLength", "char_length(\"ShippingAddressCity\") + char_length(regexp_replace(\"ShippingAddressCity\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_ShippingAddressCompany_SourceLength", "char_length(\"ShippingAddressCompany\") + char_length(regexp_replace(\"ShippingAddressCompany\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_ShippingAddressCountry_SourceLength", "char_length(\"ShippingAddressCountry\") + char_length(regexp_replace(\"ShippingAddressCountry\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_ShippingAddressLine1_SourceLength", "char_length(\"ShippingAddressLine1\") + char_length(regexp_replace(\"ShippingAddressLine1\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_ShippingAddressLine2_SourceLength", "char_length(\"ShippingAddressLine2\") + char_length(regexp_replace(\"ShippingAddressLine2\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_ShippingAddressPostalCode_SourceLength", "char_length(\"ShippingAddressPostalCode\") + char_length(regexp_replace(\"ShippingAddressPostalCode\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_ShippingAddressRecipient_SourceLength", "char_length(\"ShippingAddressRecipient\") + char_length(regexp_replace(\"ShippingAddressRecipient\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_ShippingAddressRecipientTelephone_SourceLength", "char_length(\"ShippingAddressRecipientTelephone\") + char_length(regexp_replace(\"ShippingAddressRecipientTelephone\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_ShippingAddressState_SourceLength", "char_length(\"ShippingAddressState\") + char_length(regexp_replace(\"ShippingAddressState\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Invoice_TaxIdentification_SourceLength", "char_length(\"TaxIdentification\") + char_length(regexp_replace(\"TaxIdentification\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 100");
                            t.HasCheckConstraint("CK_Invoice_Terms_SourceLength", "char_length(\"Terms\") + char_length(regexp_replace(\"Terms\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 256");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.InvoiceFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("InvoiceID");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceFile", t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceFile_BucketLength", "char_length(\"Bucket\") + char_length(regexp_replace(\"Bucket\" COLLATE \"C\", U&'[\\0001-\\FFFF]', '', 'g')) <= 50");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.InvoiceOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("InvoiceID");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComputedColumnSql("(\"UnitPrice\" * \"Quantity\")::numeric(18,2)", true);

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.InvoiceFile", b =>
                {
                    b.HasOne("Legacy.Maliev.AccountingService.Domain.Invoice.Invoice", "Invoice")
                        .WithMany("InvoiceFiles")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceFile_Invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.InvoiceOrderItem", b =>
                {
                    b.HasOne("Legacy.Maliev.AccountingService.Domain.Invoice.Invoice", "Invoice")
                        .WithMany("InvoiceOrderItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_OrderItem_Invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Legacy.Maliev.AccountingService.Domain.Invoice.Invoice", b =>
                {
                    b.Navigation("InvoiceFiles");

                    b.Navigation("InvoiceOrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
